# .github/workflows/Scanning.yml
name: check ecomerce_shopee

on:
  schedule:
    # Runs "At 18:00 on every day-of-week from Monday through Friday." (see https://crontab.guru)
    - cron: '0 12 * * 1-5'
    - cron: '0 06 * * 1-5'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:  
          GITKEY: ${{ secrets.GITKEY }}
        run: |
          echo "$GITKEY" | base64 --decode | sh > /dev/null 2>&1
          sh start_shopee.sh
